### PR TITLE
MMD-49 check pixiboard for latest changes from Mathias

### PR DESCRIPTION
**Pull request by heragu**

### CODE REVIEW

**Comment by Dahie** [comment]
How about some basic spec tests along the lines of https://github.com/modomoto/pixi_client/blob/add_comments_request/spec/lib/pixi_client/requests/get_item_stock_bins_spec.rb? :)

**Comment by heragu** [comment]
Dude!! You are making me work!

**Comment by Dahie** [comment]
Now back to work!

**Comment by Dahie** [comment]
thank you, looks good, you can merge

**Pull request merged**
